# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'NoticeBoard' do

pod 'SwiftyJSON', '~> 2.1'
pod 'Alamofire', '~> 1.1'
pod 'Refresher', '~> 0.1.1'

end

target 'NoticeBoardTests' do

end
